{"uid":"d13fd2922b13a8fa","name":"T20: Update user info with an invalid email.","fullName":"tests.test_user_authentication.TestUserAuthentication#test_update_user_info_with_invalid_email","historyId":"816aeb0a7bb5505d8d81e499c4d96038","time":{"start":1737378293302,"stop":1737378293826,"duration":524},"status":"failed","statusMessage":"AssertionError: Expected status code 400, but got 200. Response: {'_id': '678e49f56eb12444f2b46800', 'name': 'Carolyn', 'email': 'brianlewis', 'accessToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM3MzgxODkzfQ.WFntO2Jtr0HJJxPwi2xyTXlk6lhqXmIh-gszrveo24A', 'refreshToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM5OTcwMjkzfQ.bkUQ9FTquHTzURxH3jMVf6Zs1ZGnqHQLaGoDqLGU11Q', 'phone': '941.987.5515x336', 'birthday': '2019-10-12', 'skype': 'asanders', 'userImgUrl': 'https://dummyimage.com/586x939', 'userTasks': []}","statusTrace":"self = <test_user_authentication.TestUserAuthentication object at 0x000001D25B4E1040>\n\n    @pytest.mark.order(20)\n    @allure.title(\"T20: Update user info with an invalid email.\")\n    def test_update_user_info_with_invalid_email(self):\n        user = self.api_user_auth.create_user()\n>       self.api_user_auth.update_user_info_with_invalid_email(Token=user.data.accessToken)\n\ntests\\test_user_authentication.py:116: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices\\UserAuth\\api_user_auth.py:241: in update_user_info_with_invalid_email\n    self.assert_status(response, 400)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.UserAuth.api_user_auth.UserAuthAPI object at 0x000001D25B5E8830>, response = <Response [200]>, expected_status = 400\n\n    def assert_status(self, response, expected_status):\n>       assert response.status_code == expected_status, \\\n            (f\"Expected status code {expected_status}, but got {response.status_code}. Response: {response.json()}\")\nE       AssertionError: Expected status code 400, but got 200. Response: {'_id': '678e49f56eb12444f2b46800', 'name': 'Carolyn', 'email': 'brianlewis', 'accessToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM3MzgxODkzfQ.WFntO2Jtr0HJJxPwi2xyTXlk6lhqXmIh-gszrveo24A', 'refreshToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM5OTcwMjkzfQ.bkUQ9FTquHTzURxH3jMVf6Zs1ZGnqHQLaGoDqLGU11Q', 'phone': '941.987.5515x336', 'birthday': '2019-10-12', 'skype': 'asanders', 'userImgUrl': 'https://dummyimage.com/586x939', 'userTasks': []}\n\nutils\\helper.py:13: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1737378287248,"stop":1737378287249,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"_xunit_setup_method_fixture_TestUserAuthentication","time":{"start":1737378293302,"stop":1737378293302,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"testStage":{"status":"failed","statusMessage":"AssertionError: Expected status code 400, but got 200. Response: {'_id': '678e49f56eb12444f2b46800', 'name': 'Carolyn', 'email': 'brianlewis', 'accessToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM3MzgxODkzfQ.WFntO2Jtr0HJJxPwi2xyTXlk6lhqXmIh-gszrveo24A', 'refreshToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM5OTcwMjkzfQ.bkUQ9FTquHTzURxH3jMVf6Zs1ZGnqHQLaGoDqLGU11Q', 'phone': '941.987.5515x336', 'birthday': '2019-10-12', 'skype': 'asanders', 'userImgUrl': 'https://dummyimage.com/586x939', 'userTasks': []}","statusTrace":"self = <test_user_authentication.TestUserAuthentication object at 0x000001D25B4E1040>\n\n    @pytest.mark.order(20)\n    @allure.title(\"T20: Update user info with an invalid email.\")\n    def test_update_user_info_with_invalid_email(self):\n        user = self.api_user_auth.create_user()\n>       self.api_user_auth.update_user_info_with_invalid_email(Token=user.data.accessToken)\n\ntests\\test_user_authentication.py:116: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices\\UserAuth\\api_user_auth.py:241: in update_user_info_with_invalid_email\n    self.assert_status(response, 400)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.UserAuth.api_user_auth.UserAuthAPI object at 0x000001D25B5E8830>, response = <Response [200]>, expected_status = 400\n\n    def assert_status(self, response, expected_status):\n>       assert response.status_code == expected_status, \\\n            (f\"Expected status code {expected_status}, but got {response.status_code}. Response: {response.json()}\")\nE       AssertionError: Expected status code 400, but got 200. Response: {'_id': '678e49f56eb12444f2b46800', 'name': 'Carolyn', 'email': 'brianlewis', 'accessToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM3MzgxODkzfQ.WFntO2Jtr0HJJxPwi2xyTXlk6lhqXmIh-gszrveo24A', 'refreshToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM5OTcwMjkzfQ.bkUQ9FTquHTzURxH3jMVf6Zs1ZGnqHQLaGoDqLGU11Q', 'phone': '941.987.5515x336', 'birthday': '2019-10-12', 'skype': 'asanders', 'userImgUrl': 'https://dummyimage.com/586x939', 'userTasks': []}\n\nutils\\helper.py:13: AssertionError","steps":[{"name":"Create a new user.","time":{"start":1737378293302,"stop":1737378293616,"duration":314},"status":"passed","steps":[],"attachments":[{"uid":"8fbec6e7ede30132","name":"API Response","source":"8fbec6e7ede30132.json","type":"application/json","size":516}],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":1},{"name":"Update user info with an invalid email.","time":{"start":1737378293616,"stop":1737378293826,"duration":210},"status":"failed","statusMessage":"AssertionError: Expected status code 400, but got 200. Response: {'_id': '678e49f56eb12444f2b46800', 'name': 'Carolyn', 'email': 'brianlewis', 'accessToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM3MzgxODkzfQ.WFntO2Jtr0HJJxPwi2xyTXlk6lhqXmIh-gszrveo24A', 'refreshToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM5OTcwMjkzfQ.bkUQ9FTquHTzURxH3jMVf6Zs1ZGnqHQLaGoDqLGU11Q', 'phone': '941.987.5515x336', 'birthday': '2019-10-12', 'skype': 'asanders', 'userImgUrl': 'https://dummyimage.com/586x939', 'userTasks': []}\n","statusTrace":"  File \"C:\\Users\\Pavlo\\Desktop\\Goose_Tracker_API_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pavlo\\Desktop\\Goose_Tracker_API_testing\\services\\UserAuth\\api_user_auth.py\", line 241, in update_user_info_with_invalid_email\n    self.assert_status(response, 400)\n  File \"C:\\Users\\Pavlo\\Desktop\\Goose_Tracker_API_testing\\utils\\helper.py\", line 13, in assert_status\n    assert response.status_code == expected_status, \\\n","steps":[],"attachments":[],"parameters":[{"name":"Token","value":"'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWY1NmViMTI0NDRmMmI0NjgwMCIsImlhdCI6MTczNzM3ODI5MywiZXhwIjoxNzM3MzgxODkzfQ.WFntO2Jtr0HJJxPwi2xyTXlk6lhqXmIh-gszrveo24A'"}],"stepsCount":0,"attachmentStep":false,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":0}],"attachments":[],"parameters":[],"stepsCount":2,"attachmentStep":false,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":1},"afterStages":[{"name":"_xunit_setup_method_fixture_TestUserAuthentication::0","time":{"start":1737378293837,"stop":1737378293837,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"labels":[{"name":"feature","value":"User Authentication"},{"name":"tag","value":"order(20)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_authentication"},{"name":"subSuite","value":"TestUserAuthentication"},{"name":"host","value":"DESKTOP-0R2QBDF"},{"name":"thread","value":"848-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_authentication"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["order(20)"]},"source":"d13fd2922b13a8fa.json","parameterValues":[]}